In [ ]:
# Part 1 Containers

You must execute the next cell, which we will refer to as the **data cell**, to do the problems in this section.

In [ ]:
# Data cell

epsilon_left = 'abcde'
epsilon_right = 'zyxwv'
epsilon = list(zip(epsilon_right,epsilon_left))
fruit = ['tomato','cabbage','rambutan','persimmon','mangosteen']
frittata = {'alpha': epsilon_right + epsilon_left,
            'beta': epsilon_left + epsilon_right,
            'delta': fruit,
            'gamma': dict(epsilon)}

Using the containers in the data cell, write a single Python expression (so, **not** a for-loop) which returns the given values.  Sometimes there are actually many possible answers.  Try for the simplest.

# 1.1

Return `'de'`.

In [ ]:
# Solution :

frittata['beta'][3:5]
epsilon_left[3:]
epsilon_left[-2:]

'de'

##### **Logic Explanation - (1.1) :**

- We have created a container - dictionary **`'frittata'`**, in which we have created **`beta`** by passing **`epsilon_left + epsilon_right`**.
- So, we are using this container to retrieve the value **`'de'`**.

---

# 1.2

Return `'wvab'`.

In [ ]:
# Solution :

frittata['alpha'][3:7]
epsilon_right[-2:]+epsilon_left[:-3]
epsilon_right[3:]+epsilon_left[:2]

'wvab'

##### **Logic Explanation - (1.2) :**

- We have created a container - dictionary **`'frittata'`**, in which we have created **`alpha`** by passing **`epsilon_right + epsilon_left`**.
- So, we are using this container to retrieve the value **`'wvab'`**.

---

# 1.3

Return `'rambutan'`.

In [ ]:
# Solution :

frittata['delta'][2]
fruit[2]
fruit[-3]

'rambutan'

##### **Logic Explanation - (1.3) :**

- We have created a container - dictionary **`'frittata'`**, in which we have created **`delta`** by passing **`fruit`** list.
- So, we are using this container to retrieve the value **`'rambutan'`**.

---

# 1.4

Return `'sim'`.

In [ ]:
# Solution :

frittata['delta'][3][3:6]
fruit[3][3:6]
fruit[-2][-6:-3]

'sim'

##### **Logic Explanation - (1.4) :**

- We have created a container - dictionary **`'frittata'`**, in which we have created **`delta`** by passing **`fruit`** list.
- So, we are using this container to retrieve the value **`'sim'`**.

---

# 1.5

Return {'z': 'a', 'y': 'b', 'x': 'c', 'w': 'd', 'v': 'e'}

In [ ]:
# Solution :

frittata['gamma']
dict(epsilon)

{'v': 'e', 'w': 'd', 'x': 'c', 'y': 'b', 'z': 'a'}

##### **Logic Explanation  - (1.5) :**

- We have created a container - dictionary **`'frittata'`**, in which we have created **`gamma`** by creating dictionary of **`epsilon`** list.
- So, we are using this container to retrieve the value **`{'z': 'a', 'y': 'b', 'x': 'c', 'w': 'd', 'v': 'e'}`**.

- **NOTE:** Here, we are getting the ASCENDING Ordered Dictionary **`{'v': 'e', 'w': 'd', 'x': 'c', 'y': 'b', 'z': 'a'}`** (in contrast with the expected Result Dictionary **`{'z': 'a', 'y': 'b', 'x': 'c', 'w': 'd', 'v': 'e'}`**, because the default behaviour of a Dictionary is to sort the (key, value) pairs in the ASCENDING Order.

---

# 1.6

Return 

`[('x', 'c'), ('w', 'd')]`

In [ ]:
# Solution :

epsilon[2:4]

[('x', 'c'), ('w', 'd')]

##### **Logic Explanation - (1.6) :**

- We have created a list **`'epsilon'`**, in which we have passed **`list(epsilon_right, epsilon_left)`**.
- So, we are using this list to retrieve the result value **`[('x', 'c'), ('w', 'd')]`**.

---

# 1.7

Compare the results in the next two cells.

Explain why one expression raises an `Exception` and the other does not, even
though both involve accessing data defined in `epsilon`.

In [ ]:
epsilon['x']

TypeError: ignored

In [ ]:
frittata['gamma']['x']

'c'

### **Answer Explanation - (1.7) :**

#### 1) `epsilon['x']`
- In the first expression - `epsilon['x']` : we have passed a string as a index for accessing a List.
- As per the syntax rules, while accessing the List elements, we cannot use string for passing as an index.
- Thus, we need to correct this error by passing an integer as an index.
- Also to note here, epsilon is not a dictionary. it is just a combination of two strings converted into a list with 2 values into each element.





In [ ]:
# Correct way of retrieveing value for index 'x':
epsilon[2][1]

'c'

#### 2) `frittata['gamma']['x']`
- In the second expression - `frittata['gamma']['x']` : As in the given data, we have created `frittata` as a Container - Dictionary.
- As per the syntax rules, Dictionaries can be accessed using a key.
- Here, we have only one Primary Dictionary, so we got to use only 1 key as `['gamma']` and the `['x']` for referencing the element's key.

---

# Part 2 Functions, Loops

You must execute the data cell to do the problems in this section.

In [ ]:
# Data cell

import numpy as np

xx = np.arange(0,26,4)

sad_story = """Billy the Kid lived in the Wild West long ago .
He was an outlaw .
He was friends with Pat Garrett who was a lawman .
One day Pat Garrett had to bring Billy the Kid in .
Billy would not come .
They had a gunfight and Pat shot his friend Billy .
"""

# 2.1

Write a loop (it can be a list comprehension) that computes a list of the numbers in `xx` that arew divisible by 3.

Do not import any python packages to help (that would suggest that you have
not been doing the material in the first part of the class and have done a google search to solve this problem).

You may find it useful to be reminded of the `%`-operator:

x%y

returns the remainder when x is divided by y.  So, for example,

```
>>> 17%5
2
```

Note: although `xx` is a numpy array, for the purposes of this section you
may treat it as if it were a list.

In [ ]:
# Solution :

[i for i in xx if i % 3 == 0]

[0, 12, 24]

##### **Logic Explanation  - (2.1) :**

- I have used a **`%-operator`** to check if the element is divisible by 3 and the remainder obtained is 0, using List Comprehension.

---

# 2.2

Write a for-loop (it may be a list comprehension) that builds a list containing all instances of the letter  `t` in `sad_story`

In [ ]:
# Solution :

# Finding the indexes of words in 'sad_story' which contains 't':
index_words_having_t = [i for i in range(len(sad_story.split())) if 't' in (sad_story.split())[i] ]

# Finding the words in 'sad_story' which contains 't':
words_having_t = [w for w in sad_story.split() if 't' in w]

# Final Result displaying (index, word instance containing 't'):
all_words_having_t = list(zip(index_words_having_t, words_having_t))

all_words_having_t

[(1, 'the'),
 (5, 'the'),
 (7, 'West'),
 (14, 'outlaw'),
 (19, 'with'),
 (20, 'Pat'),
 (21, 'Garrett'),
 (29, 'Pat'),
 (30, 'Garrett'),
 (32, 'to'),
 (35, 'the'),
 (41, 'not'),
 (47, 'gunfight'),
 (49, 'Pat'),
 (50, 'shot')]

##### **Logic Explanation - (2.2) :**

- Firstly, I am finding the **`indexes`** of elements of **`sad_story`** which contain the letter **'t'** into them.
- Secondly, i am finding for the **`words`** in the **`sad_story`** list which contain the letter **'t'** into them.
- Finally, I am merging the above two results into a consolidated List and then displaying the result.

---

# 2.3

Write a for-loop (it may be a list comprehension) that builds a list containing all instances of the word  `the` in `sad_story`.

In [ ]:
# Solution :

# Finding the indexes of words in 'sad_story' which contains 't':
index_words_having_the = [i for i in range(len(sad_story.split())) if 'the' in (sad_story.split())[i] ]

# Finding the words in 'sad_story' which contains 't':
words_having_the = [w for w in sad_story.split() if 'the' in w]

# Final Result displaying (index, word instance containing 't'):
all_words_having_the = list(zip(index_words_having_the, words_having_the))

all_words_having_the

[(1, 'the'), (5, 'the'), (35, 'the')]

##### **Logic Explanation - (2.3) :**

- Firstly, I am finding the **`indexes`** of elements of **`sad_story`** which contain **'the'** into them.
- Secondly, i am finding for the **`words`** in the **`sad_story`** list which contain **'the'** into them.
- Finally, I am merging the above two results into a consolidated List and then displaying the result.

---

# 2.4

Write a for loop that creates a dictionary containing the counts of all the words
in `sad_story`.  Do not import any Python modules. 

Call your dictonary `wd_cts`.  If your program is correct `wd_cts`
should contain the following count:

```
>>> wd_counts['in']
2
```

In [ ]:
# Solution :

wd_counts = dict()
for w in sad_story.split():
    if w in wd_counts:
        wd_counts[w] += 1
    else:
        wd_counts[w] = 1

In [ ]:
wd_counts['in']

2

##### **Logic Explanation - (2.4) :**

- I have started with defining the **`wd_counts`** as dictionary.
- Dictionary makes it easy to store and access the elements and their frequency occurances into them.
- So, I first searched if the word is present in the search text, I have immediately added that word into wd_counts dictionary.
- after every occurence, our search counter will get incremented by 1 and it will get added into the wd_counts dictionary.
- Finally, when we search any word's occurance into wd_counts, we get the total frequency count for that word.

---

# 2.5

Write a **function** `find_word_forms` that takes a string `text_str` and a word `form` as its **two** arguments and returns all **words** in `text_str` that end with `form`.
Write this without importing any Python modules.

Here are some tests that your function should pass:

```
>>> find_word_forms(sad_story, 'ing')
['bring']
>>> find_word_forms(sad_story, 'ed')
['lived']
>>> find_word_forms("He 's sending birds on the wing .", 'ing')
['sending', 'wing']
>>> find_word_forms(sad_story, 'g')
['long', 'bring']
```

Hint:  You may find it helpful to remember the
string method `endswith`.

In [ ]:
# Solution :

def find_word_forms(text_str, form):
  text_str_words = text_str.split()
  result = []
  for word in text_str_words:
      if word.endswith(form):
          result.append(word)
  return result

In [ ]:
find_word_forms(sad_story, 'ing')

['bring']

In [ ]:
find_word_forms(sad_story, 'ed')

['lived']

In [ ]:
find_word_forms("He 's sending birds on the wing .", 'ing')

['sending', 'wing']

In [ ]:
find_word_forms(sad_story, 'g')

['long', 'bring']

##### **Logic Explanation - (2.5) :**

- I have defined the function **`find_word_forms`** by passing the text string and the word form.
- Next, I have splitted the words of the text using **`split()`**, as it might be present in form of a string or a list.
- Then, I have defined the result list as blank at initial point.
- Further, I have searched for the word in Text String which ends with expected form using the function **`endswith`**.
- Finally, whichever words aho have the form present into them, will get added to the Result list.

---

# 2.6

Write a function that converts degrees to radians. You are allowed
to use the following import statement:

```
from numpy import pi
```

The formula is

```
Radians = (Degrees/360) * 2 * pi
```

Here are some tests

```
>>> deg2rad(360)
6.283185307179586
>>> deg2rad(90)
1.5707963267948966
>>> deg2rad(72)
1.2566370614359172
```

In [ ]:
# Solution :

from numpy import pi

def deg2rad(value):
    if value == None:
      print ('0')
    else:
      return (value/360) * 2 * pi

deg2rad(360)

6.283185307179586

In [ ]:
deg2rad(90)

1.5707963267948966

In [ ]:
deg2rad(72)

1.2566370614359172

##### **Logic Explanation - (2.6) :**

- Initially, I have used the **`numpy`** library to access the function **`pi`**.
- Further, I have defined a function **`deg2rad`** which converts the value given into degree to radians.
- If no appropriate value is given then the function will return **`None`**.

---

# Part 3 Numpy arrays

You must execute the next cell to do the problems in this section.

In [ ]:
# Data cell

import numpy as np

xx = np.arange(4,61,4)

yy = xx.reshape((3,5))

# 3.1

Write a single Python expression that returns 12 from `xx`

In [ ]:
# Solution :

xx[2]

12

##### **Logic Explanation - (3.1) :**

- I have used the **Array Index** to retrieve the value **12** from the **`xx`** list.

---

# 3.2

Write a single Python expression  that returns all members of `xx` divisible by 8.
Hint: Use a splice.

In [ ]:
# Solution :

xx[1::2]

array([ 8, 16, 24, 32, 40, 48, 56])

##### **Logic Explanation - (3.2) :**

- I have used **`splice`** to get all the values which are **completely divisible by 8**.

---

# 3.3

Write a single Python expression  that returns all members of `xx` 
greater than 16.  You may use a splice if you wish.

In [ ]:
# Solution :

xx[xx > 16]

array([20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60])

##### **Logic Explanation - (3.3) :**

- I have used the **Comparison Operator** **`>`** to check for all the elements which are greater than 16.

---

# 3.4

Write a single Python expression  that returns the following
1D array from `yy`.

```
array([24, 28, 32, 36, 40])
```

In [ ]:
# Solution :

yy[1,:]

array([24, 28, 32, 36, 40])

##### **Logic Explanation - (3.4) :**

- I have used the **Row Indexes** to fing the resultant array.

---

# 3.5

Write a single Python expression  that returns the following
2D array from `yy`.

```
array([[ 4,  8, 12, 16, 20],
       [24, 28, 32, 36, 40]])
```

In [ ]:
# Solution :

yy[0:2,:]

array([[ 4,  8, 12, 16, 20],
       [24, 28, 32, 36, 40]])

##### **Logic Explanation - (3.5) :**

- I have used the **Row Indexes** to fing the resultant array.

---

# 3.6

Write a single Python expression  that returns the following
2D array from `yy`.

```
array([[32, 36],
       [52, 56]])
```

In [ ]:
# Solution :

yy[1:3,2:4]

array([[32, 36],
       [52, 56]])

##### **Logic Explanation - (3.6) :**

- I have used the **Row Indexes** as well as **Column Indexes** to fing the resultant array.

---

# Part 4  Wine Data

In this exercise set, we load wine data. This is a multi class dataset that has data for three different wine types  (stored in `target` below) corresponding to three
different cultivators in a particular region of Italy.  These will just
be referred to as class_1 calss_2 and class_3 in the description below
and in the questions.
The chemical properties of the wine stored in the 2D numpy array `data` below are sufficient to identity the cultivator, but it's a challenging classification problem.

Wine recognition dataset
-----------------------------

**Data Set Characteristics:**

    :Number of Instances: 178
    :Number of Attributes: 13 numeric, predictive attributes and the class
    :Attribute Information:
 		- Alcohol
 		- Malic acid
 		- Ash
		- Alcalinity of ash  
 		- Magnesium
		- Total phenols
 		- Flavanoids
 		- Nonflavanoid phenols
 		- Proanthocyanins
		- Color intensity
 		- Hue
 		- OD280/OD315 of diluted wines
 		- Proline

    - class:
            - class_0
            - class_1
            - class_2
		
     
    The wine atributes listed in their column order.
    
    ============================= ==== ===== ======= =====
                                   Min   Max   Mean     SD
    ============================= ==== ===== ======= =====
    Alcohol:                      11.0  14.8    13.0   0.8
    Malic Acid:                   0.74  5.80    2.34  1.12
    Ash:                          1.36  3.23    2.36  0.27
    Alcalinity of Ash:            10.6  30.0    19.5   3.3
    Magnesium:                    70.0 162.0    99.7  14.3
    Total Phenols:                0.98  3.88    2.29  0.63
    Flavanoids:                   0.34  5.08    2.03  1.00
    Nonflavanoid Phenols:         0.13  0.66    0.36  0.12
    Proanthocyanins:              0.41  3.58    1.59  0.57
    Colour Intensity:              1.3  13.0     5.1   2.3
    Hue:                          0.48  1.71    0.96  0.23
    OD280/OD315 of diluted wines: 1.27  4.00    2.61  0.71
    Proline:                       278  1680     746   315
    ============================= ==== ===== ======= =====

    :Missing Attribute Values: None
    :Class Distribution: class_0 (59), class_1 (71), class_2 (48)
    :Creator: R.A. Fisher
    :Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)
    :Date: July, 1988

This is a copy of UCI ML Wine recognition datasets.
https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data

The data is the results of a chemical analysis of wines grown in the same
region in Italy by three different cultivators. There are thirteen different
measurements taken for different constituents found in the three types of
wine.

Original Owners: 

Forina, M. et al, PARVUS - 
An Extendible Package for Data Exploration, Classification and Correlation. 
Institute of Pharmaceutical and Food Analysis and Technologies,
Via Brigata Salerno, 16147 Genoa, Italy.

Citation:

Lichman, M. (2013). UCI Machine Learning Repository
[https://archive.ics.uci.edu/ml]. Irvine, CA: University of California,
School of Information and Computer Science. 

You must evaluate the next cell to do the problems in this section.

In [ ]:
# Data Cell

from sklearn.datasets import load_wine
wdata = load_wine()
data = wdata.data
target = wdata.target

**4.0**  

Write a Python expression that returns s Boolean array defining
the set of rows of the `data` array with magnesium level greater than 99.7  and 
Proanthocyanins level less than 1.59.

In [ ]:
# Solution :

magnesium_col = data[:,4]
proanthocyanins_col = data[:,8]

print( (magnesium_col > 99.7) & (proanthocyanins_col < 1.59))

print( ((magnesium_col > 99.7) & (proanthocyanins_col < 1.59)).shape)

[False  True False False False False False  True False False False False
 False False False  True False False False False False False False False
 False False False False False False False False False  True  True False
  True False False False False False False False False  True False False
 False False False False False False False False False False False False
  True  True False False  True False False False  True False  True False
 False False False False False  True False False False False False False
 False False False False False False False False False False False False
  True False False False False False False False False False False False
 False False False False  True False False False False False False False
 False False False False False False False False False False  True  True
 False  True False False False False False  True False False False False
  True  True False False False  True  True  True  True False  True False
 False False False False False  True  True  True Fa

##### **Logic Explanation - (4.0) :**

- Initially, I have stored the individual results for the **`magnesium level > 99.7`** and **`Proanthocyanins level < 1.59`**.
- Later, I have displayed the final result of **Boolean Array** using the **Logical Operator '&'**.

---

**4.1**

Write a Python expression that returns the rows of the `data` array 
representing  wine samples with  magnesium level greater than 99.7  and 
Proanthocyanins level less than 1.59.

In [ ]:
# Solution :

magnesium_col = data[:,4]
proanthocyanins_col = data[:,8]

data[(magnesium_col > 99.7) & (proanthocyanins_col < 1.59)]

array([[1.320e+01, 1.780e+00, 2.140e+00, 1.120e+01, 1.000e+02, 2.650e+00,
        2.760e+00, 2.600e-01, 1.280e+00, 4.380e+00, 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.406e+01, 2.150e+00, 2.610e+00, 1.760e+01, 1.210e+02, 2.600e+00,
        2.510e+00, 3.100e-01, 1.250e+00, 5.050e+00, 1.060e+00, 3.580e+00,
        1.295e+03],
       [1.363e+01, 1.810e+00, 2.700e+00, 1.720e+01, 1.120e+02, 2.850e+00,
        2.910e+00, 3.000e-01, 1.460e+00, 7.300e+00, 1.280e+00, 2.880e+00,
        1.310e+03],
       [1.376e+01, 1.530e+00, 2.700e+00, 1.950e+01, 1.320e+02, 2.950e+00,
        2.740e+00, 5.000e-01, 1.350e+00, 5.400e+00, 1.250e+00, 3.000e+00,
        1.235e+03],
       [1.351e+01, 1.800e+00, 2.650e+00, 1.900e+01, 1.100e+02, 2.350e+00,
        2.530e+00, 2.900e-01, 1.540e+00, 4.200e+00, 1.100e+00, 2.870e+00,
        1.095e+03],
       [1.328e+01, 1.640e+00, 2.840e+00, 1.550e+01, 1.100e+02, 2.600e+00,
        2.680e+00, 3.400e-01, 1.360e+00, 4.600e+00, 1.090e+00, 2.780e+00,
        8.80

##### **Logic Explanation - (4.1) :**

- Initially, I have stored the individual results for the **`magnesium level > 99.7`** and **`Proanthocyanins level < 1.59`**.
- Later, I have displayed the final result of **Data Array** using the **Logical Operator '&'**.

---

**4.2**

How many such rows are there?  Show the computation.

In [ ]:
# Solution :

# Finding total number of values satisfying the conditions
len( data[(magnesium_col > 99.7) & (proanthocyanins_col < 1.59)] )

35

#### **Answer Explanation - (4.2) :**

Using **Data Array** from **4.1**, there are a total of **35 values** in the Wine Recognition Dataset, whose **'`magnesium level > 99.7`'** and **'`Proanthocyanins level < 1.59`'**.

- I have used the **`len`** function to get the total count of the rows.

---

**4.3**

Write a Python expression that returns the rows of the `data` array 
representing wine samples such that they are not of class_1 and they
have magnesium level greater than 99.7  and 
Proanthocyanins level less than 1.59.

In [ ]:
# Solution :

magnesium_col = data[:,4]
proanthocyanins_col = data[:,8]

data[(magnesium_col > 99.7) & (proanthocyanins_col < 1.59) & (target != 1)]

array([[1.320e+01, 1.780e+00, 2.140e+00, 1.120e+01, 1.000e+02, 2.650e+00,
        2.760e+00, 2.600e-01, 1.280e+00, 4.380e+00, 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.406e+01, 2.150e+00, 2.610e+00, 1.760e+01, 1.210e+02, 2.600e+00,
        2.510e+00, 3.100e-01, 1.250e+00, 5.050e+00, 1.060e+00, 3.580e+00,
        1.295e+03],
       [1.363e+01, 1.810e+00, 2.700e+00, 1.720e+01, 1.120e+02, 2.850e+00,
        2.910e+00, 3.000e-01, 1.460e+00, 7.300e+00, 1.280e+00, 2.880e+00,
        1.310e+03],
       [1.376e+01, 1.530e+00, 2.700e+00, 1.950e+01, 1.320e+02, 2.950e+00,
        2.740e+00, 5.000e-01, 1.350e+00, 5.400e+00, 1.250e+00, 3.000e+00,
        1.235e+03],
       [1.351e+01, 1.800e+00, 2.650e+00, 1.900e+01, 1.100e+02, 2.350e+00,
        2.530e+00, 2.900e-01, 1.540e+00, 4.200e+00, 1.100e+00, 2.870e+00,
        1.095e+03],
       [1.328e+01, 1.640e+00, 2.840e+00, 1.550e+01, 1.100e+02, 2.600e+00,
        2.680e+00, 3.400e-01, 1.360e+00, 4.600e+00, 1.090e+00, 2.780e+00,
        8.80

##### **Logic Explanation - (4.3) :**

- Initially, I have stored the individual results for the **`magnesium level > 99.7`** and **`Proanthocyanins level < 1.59`**.
- Later, I have displayed the final result of **Data Array** using the **Logical Operator '&'** and by using filter condition of Class as **`(target != 1)`**.

---

**4.4**

How many such rows are there?  Show the computation.

In [ ]:
# Solution :

# Finding total number of values satisfying the conditions
len( data[(magnesium_col > 99.7) & (proanthocyanins_col < 1.59) & (target != 1)] )

27

#### **Answer Explanation - (4.4) :**

Using **Data Array** from **4.3**, there are a total of **27 values** in the Wine Recognition Dataset, who **'`DO NOT belong to Class 1`'** and whose **'`magnesium level > 99.7`'** and **'`Proanthocyanins level< 1.59`'**.

- I have used the **`len`** function to get the total count of the rows.

---